### ISSUE TITLE
Default component

### ISSUE THREAD

**Issue by geniqtech** [brunocfalcao/blade-feather-icons#18]
In blade icons, we can use the following syntax:
`<x-icon name="camera"/>`

Is there anything similar for blade-feather-icons?

I'm trying to generate dynamic menu with icons. Both methods below does not seem to work:
`<x-feathericon-{{ $menu['icon'] }} />`

`<x-feathericon name="{{ $menu['icon'] }}" />`

**Comment by brunocfalcao** [comment]
Hi there, sorry for the delay, I think you can't generate blade component directives dynamically. Did you try to use it with a fixed name? like

```
<x-feathericon-feather />

```

**Comment by brunocfalcao** [comment]
closing for now. tested it and it's working well, thanks
