### ISSUE TITLE
Compatibility with Laravel 9.0

### ISSUE THREAD

**Issue by CeriseGoutPelican** [brunocfalcao/blade-feather-icons#23]
Hello,

I am trying to upgrade my project to Laravel 9.0 from 8.75 and it seems that `brunocflacaeo/blade-feather-icons` is not compatible with the latest releases.

```
    - brunocfalcao/blade-feather-icons[v0.1.0, ..., v0.2.0] require php ^7.2 -> your php version (8.1.2) does not satisfy that requirement.
    - brunocfalcao/blade-feather-icons v1.0.0 requires php ^7.3 -> your php version (8.1.2) does not satisfy that requirement.
    - brunocfalcao/blade-feather-icons[v1.1.0, ..., v1.1.3] require blade-ui-kit/blade-icons ^0.5 -> found blade-ui-kit/blade-icons[0.5.0, 0.5.1] but it conflicts with your root composer.json require (^1.2).
    - brunocfalcao/blade-feather-icons[dev-dependabot/npm_and_yarn/follow-redirects-1.14.7, dev-dependabot/npm_and_yarn/url-parse-1.5.3, dev-dependabot/npm_and_yarn/path-parse-1.0.7, dev-master, 2.0.0, ..., v2.0.1] require illuminate/support ^7.14|^8.0 -> found illuminate/support[v7.14.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
 ```

I am not sure how to deal with this problem since composer seems to highlight the PHP version (but I was already running PHP 8.1.2 prior to Laravel update).

Any help would be greatly appreciated.

**Comment by endriu3314** [comment]
> I am not sure how to deal with this problem since composer seems to highlight the PHP version (but I was already running PHP 8.1.2 prior to Laravel update).

#24 

It should be straight forward as that PR does

**Comment by brunocfalcao** [comment]
Hi there,

Just published a new version with compatibility for L9.

Sorry for the delay.

Best,
Bruno
